export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as SignUpInputAccountInfo } from './SignUpInputAccountInfo'
export { default as UploadAvatar } from './UploadAvatar'
export { default as StudentBasicAccountInfo } from './StudentBasicAccountInfo'
export { default as TeacherBasicAccountInfo } from './TeacherBasicAccountInfo'
export { default as UpdateAccountInfoItem } from './UpdateAccountInfoItem'
